version: "3.9"
services:
  backend-green:
    image: "${BACKEND_IMAGE}:${IMAGE_TAG}"
    env_file: /opt/rmit/backend/.env
    ports:
      - "${BACKEND_GREEN_PORT:-3002}:3000"
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:${BACKEND_GREEN_PORT:-3002}/api/health"]
      interval: 10s
      timeout: 3s
      retries: 10

  frontend-green:
    image: "${FRONTEND_IMAGE}:${IMAGE_TAG}"
    volumes:
      - /var/www/frontend-green:/usr/share/nginx/html
    environment:
      - NGINX_PORT=8080
    restart: always
