version: "3.9"
services:
  backend:
    image: "${BACKEND_IMAGE}:${IMAGE_TAG}"
    env_file: /opt/rmit/backend/.env
    ports:
      - "${BACKEND_STAGING_PORT:-3000}:3000"
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:3000/api/health"]
      interval: 10s
      timeout: 3s
      retries: 10

  frontend:
    image: "${FRONTEND_IMAGE}:${IMAGE_TAG}"
    volumes:
      - /var/www/frontend-staging:/usr/share/nginx/html
    environment:
      - NGINX_PORT=8080
    ports:
      - "8080:8080"
    restart: always
