FROM node:18-alpine AS build

WORKDIR /app

COPY client/package*.json ./client/
WORKDIR /app/client
RUN npm ci

COPY client/ ./
RUN npm run build

#prep for nginx
FROM nginx:alpine
COPY --from=build /app/client/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]